// Generated by Xata Codegen 0.26.9. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Questions",
    columns: [
      { name: "language", type: "string" },
      { name: "prompt", type: "string" },
      { name: "explanation", type: "text" },
      { name: "choices", type: "multiple" },
      { name: "correct_choice", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Questions = InferredTypes["Questions"];
export type QuestionsRecord = Questions & XataRecord;

export type DatabaseSchema = {
  Questions: QuestionsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://codeNest-l30ngi.eu-central-1.xata.sh/db/frontend-QA",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
